// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/andreygrechin/gcphelper/pkg/organizations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockFetcher
func (_mock *MockFetcher) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFetcher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFetcher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFetcher_Expecter) Close() *MockFetcher_Close_Call {
	return &MockFetcher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFetcher_Close_Call) Run(run func()) *MockFetcher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFetcher_Close_Call) Return(err error) *MockFetcher_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFetcher_Close_Call) RunAndReturn(run func() error) *MockFetcher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SearchOrganizations provides a mock function for the type MockFetcher
func (_mock *MockFetcher) SearchOrganizations(ctx context.Context) ([]*organizations.Organization, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SearchOrganizations")
	}

	var r0 []*organizations.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*organizations.Organization, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*organizations.Organization); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*organizations.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_SearchOrganizations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchOrganizations'
type MockFetcher_SearchOrganizations_Call struct {
	*mock.Call
}

// SearchOrganizations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFetcher_Expecter) SearchOrganizations(ctx interface{}) *MockFetcher_SearchOrganizations_Call {
	return &MockFetcher_SearchOrganizations_Call{Call: _e.mock.On("SearchOrganizations", ctx)}
}

func (_c *MockFetcher_SearchOrganizations_Call) Run(run func(ctx context.Context)) *MockFetcher_SearchOrganizations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFetcher_SearchOrganizations_Call) Return(organizations1 []*organizations.Organization, err error) *MockFetcher_SearchOrganizations_Call {
	_c.Call.Return(organizations1, err)
	return _c
}

func (_c *MockFetcher_SearchOrganizations_Call) RunAndReturn(run func(ctx context.Context) ([]*organizations.Organization, error)) *MockFetcher_SearchOrganizations_Call {
	_c.Call.Return(run)
	return _c
}
