// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/andreygrechin/gcphelper/pkg/folders"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockFetcher
func (_mock *MockFetcher) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFetcher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFetcher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFetcher_Expecter) Close() *MockFetcher_Close_Call {
	return &MockFetcher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFetcher_Close_Call) Run(run func()) *MockFetcher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFetcher_Close_Call) Return(err error) *MockFetcher_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFetcher_Close_Call) RunAndReturn(run func() error) *MockFetcher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ListFolders provides a mock function for the type MockFetcher
func (_mock *MockFetcher) ListFolders(ctx context.Context, opts *folders.FetchOptions) ([]*folders.Folder, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListFolders")
	}

	var r0 []*folders.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *folders.FetchOptions) ([]*folders.Folder, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *folders.FetchOptions) []*folders.Folder); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*folders.Folder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *folders.FetchOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_ListFolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFolders'
type MockFetcher_ListFolders_Call struct {
	*mock.Call
}

// ListFolders is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *folders.FetchOptions
func (_e *MockFetcher_Expecter) ListFolders(ctx interface{}, opts interface{}) *MockFetcher_ListFolders_Call {
	return &MockFetcher_ListFolders_Call{Call: _e.mock.On("ListFolders", ctx, opts)}
}

func (_c *MockFetcher_ListFolders_Call) Run(run func(ctx context.Context, opts *folders.FetchOptions)) *MockFetcher_ListFolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *folders.FetchOptions
		if args[1] != nil {
			arg1 = args[1].(*folders.FetchOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFetcher_ListFolders_Call) Return(folders1 []*folders.Folder, err error) *MockFetcher_ListFolders_Call {
	_c.Call.Return(folders1, err)
	return _c
}

func (_c *MockFetcher_ListFolders_Call) RunAndReturn(run func(ctx context.Context, opts *folders.FetchOptions) ([]*folders.Folder, error)) *MockFetcher_ListFolders_Call {
	_c.Call.Return(run)
	return _c
}

// ListFoldersFromParent provides a mock function for the type MockFetcher
func (_mock *MockFetcher) ListFoldersFromParent(ctx context.Context, parent string, opts *folders.FetchOptions) ([]*folders.Folder, error) {
	ret := _mock.Called(ctx, parent, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListFoldersFromParent")
	}

	var r0 []*folders.Folder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *folders.FetchOptions) ([]*folders.Folder, error)); ok {
		return returnFunc(ctx, parent, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *folders.FetchOptions) []*folders.Folder); ok {
		r0 = returnFunc(ctx, parent, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*folders.Folder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *folders.FetchOptions) error); ok {
		r1 = returnFunc(ctx, parent, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_ListFoldersFromParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFoldersFromParent'
type MockFetcher_ListFoldersFromParent_Call struct {
	*mock.Call
}

// ListFoldersFromParent is a helper method to define mock.On call
//   - ctx context.Context
//   - parent string
//   - opts *folders.FetchOptions
func (_e *MockFetcher_Expecter) ListFoldersFromParent(ctx interface{}, parent interface{}, opts interface{}) *MockFetcher_ListFoldersFromParent_Call {
	return &MockFetcher_ListFoldersFromParent_Call{Call: _e.mock.On("ListFoldersFromParent", ctx, parent, opts)}
}

func (_c *MockFetcher_ListFoldersFromParent_Call) Run(run func(ctx context.Context, parent string, opts *folders.FetchOptions)) *MockFetcher_ListFoldersFromParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *folders.FetchOptions
		if args[2] != nil {
			arg2 = args[2].(*folders.FetchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFetcher_ListFoldersFromParent_Call) Return(folders1 []*folders.Folder, err error) *MockFetcher_ListFoldersFromParent_Call {
	_c.Call.Return(folders1, err)
	return _c
}

func (_c *MockFetcher_ListFoldersFromParent_Call) RunAndReturn(run func(ctx context.Context, parent string, opts *folders.FetchOptions) ([]*folders.Folder, error)) *MockFetcher_ListFoldersFromParent_Call {
	_c.Call.Return(run)
	return _c
}
